version: '3.9'

services:
  app:
    container_name: milimili-app
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file:
      - .env.production
    ports:
      - "80:80"
    restart: always
    depends_on:
      - milimili-mongo
      - milimili-redis

  milimili-mongo:
    image: mongo:6.0
    platform: linux/amd64
    container_name: milimili-mongo
    volumes:
      - mongo_data:/data/db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: milimili

  milimili-redis:
    image: redis:7-alpine
    platform: linux/amd64
    container_name: milimili-redis
    volumes:
      - redis_data:/data
    restart: always

volumes:
  mongo_data:
  redis_data:
